name: Branch Name Validation

on:
  push:
    branches:
      - '*'  # Runs on any branch push
  pull_request:
    branches:
      - '*'  # Runs on any pull request

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Verify branch name starts with "ft/" or "hf/"
      run: |
        branch_name="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
        if [[ "$branch_name" != ft/* ]] && [[ "$branch_name" != hf/* ]]; then
          echo "Branch name ($branch_name) does not start with 'ft/' or 'hf/'"
          exit 1
        else
          echo "Branch name ($branch_name) is valid."
        fi
